### PR TITLE
Added version and allowedVersion metrics

### PR DESCRIPTION
**Pull request by Cmdrd**
This should cover issue #3 with both current version and the allowed version on the network.

### CODE REVIEW

**Comment by kevinkk525** [comment]
"should"? Did you test it?
The more difficult problem here might be how to show those values in the dashboard.

**Comment by Cmdrd** [comment]
It was more if there was other stuff that was wanting to be pulled as there are no additional details.
It shows up in my metrics as, so it does work:
# HELP storj_version_info Storj version
# TYPE storj_version_info gauge
storj_version_info{version="0.30.5"} 1.0
# HELP storj_allowedVersion_info Storj allowedVersion
# TYPE storj_allowedVersion_info gauge
storj_allowedVersion_info{allowedVersion="0.29.0"} 1.0

**Comment by Cmdrd** [comment]
After some testing today with this, I have found how to display this info in the Grafana dashboard.
```
1. Create a SingleStat panel
2. Metric is storj_version_info with Format: Table
3. In Visualization, set Value -> Field to version
```
Appears for me like this:
image

**Comment by kevinkk525** [comment]
Truly awesome would be to display the number and make it red if it is less than allowed version, green if current and orange if in between. Would also make the section "up to date" obsolete.
What do you think?

**Comment by Cmdrd** [comment]
While that would be pretty sweet, because it is exposed as a string and not numeric metric that would be more difficult. I will play around with it to see if there is some PromQL functionality that will let me manipulate data like that. 

The exporter configuration would ultimately have to be modified in order to expose the information as an integer or something along those lines and that is a bit outside of my knowledge for building at this time. For now I think having 2 panels, one with the current version and the other with the allowed version will probably have to do.

**Comment by kevinkk525** [comment]
I don't know about how to do that in grafana either.

But one could make the exporter convert the version string into a breakdown of <major>.<minor>.<micro> and store those additionally. then you have 3 integer values you could use to calculate if the current version is older. Or you combine those 3 integers into one big number like <major>*100000+<minor>*100+<micro> which should give enough options unless storj decides to release a version like 0.1000.100.
Anyway storing 3 integers would be the safer and more clean approach.

**Comment by Cmdrd** [comment]
That's actually an awesome approach, could present additional individual x.y.z as major (x), minor (y), and point (z) metrics to distinguish between the levels by a metric style conversion. Or present the metric as value=(x*1000000)+(y*1000)+z. I am sure that Storj Labs will not hit 1000 or 1000000 in any sort of version numbers. Presenting a single value for comparison would make it a lot easier in Grafana to implement a compare. Current version would then look like 30005 and allowed version 29000.

**Comment by anclrii** [comment]
Let's break this down to 2 problems that we are trying to solve:

1. Expose version info as returned by api:
    * I think the suggested changes here take care of this 100% and happy to merge as is
2. Show outdated version as a single status/metric in grafana:
    * we may find a way to do this in Grafana with just the versions returned as strings (unlikely :) )
    * we can consider adding a 3-rd version metric like `storj_version_status` that will compare versions within exporter code. We can add something like https://stackoverflow.com/a/11887825

Shell I merge the PR to cross off 1 and raise a new issue for 2? What do you think?

**Comment by Cmdrd** [comment]
Good idea, let's get this moved in then tackle 2 in a separate piece of work. Raise an issue with it and we can discuss the approach we want to take there.

**Pull request merged**
