### PR TITLE
audit api changes

### PR DESCRIPTION
**Pull request by kevinkk525**
new docker image available so maybe time to merge the changes?

### CODE REVIEW

**Comment by anclrii** [comment]
I just updated and api still has 
```
  "audit": {
    "totalCount": 3076,
    "successCount": 3052,
    "alpha": 19.99999,
    "beta": 1e-05,
    "unknownAlpha": 19.99999,
    "unknownBeta": 1e-05,
    "score": 0.9999995,
    "unknownScore": 0.9999995
  },
```
Devs didn't say what version will have this changes, but that's not it.

**Comment by kevinkk525** [comment]
oh sorry, my bad. You're right. It's not in this update yet.

**Comment by Shinokama** [comment]
Guys, the time has come =)
   "audits":[
      {
         "auditScore":1,
         "suspensionScore":1,
         "onlineScore":1,
         "satelliteName":"us2.tardigrade.io:7777"
      },

**Comment by anclrii** [comment]
> Guys, the time has come =)

What version are you running and what platform? I just checked for updated for linux docker image and it's still on `1.20.2` with old api entries.

If you are running a newer version you can try this dev build with `docker pull anclrii/storj-exporter:dev`

**Comment by Shinokama** [comment]
I'm running v1.20.2 with watchtower. Btw I have already build exporter with code of the PR.

**Comment by anclrii** [comment]
This is weird. Checking again and I don't have `audits` on 1.20.2 

```
# curl -s 'http://localhost:14007/api/sno/' | jq  .version
"1.20.2"
# curl -s 'http://localhost:14007/api/sno/satellite/12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo' | jq  .audit
{
  "totalCount": 621,
  "successCount": 621,
  "alpha": 19.99999,
  "beta": 0,
  "unknownAlpha": 19.99999,
  "unknownBeta": 0,
  "score": 1,
  "unknownScore": 1
}
# curl -s 'http://localhost:14007/api/sno/satellite/12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo' | jq  .audits
null
```

Are you running on ARM by any chance? I'm on amd64.

Also just noticed I did not merge autobuild for multi-arch images into dev branch yet - I'll fix this.

**Comment by Shinokama** [comment]
with one satellite - yes,
curl -s 'http://192.168.1.20:14003/api/sno/satellite/12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo' | jq .audit
{
  "totalCount": 0,
  "successCount": 0,
  "alpha": 1,
  "beta": 0,
  "unknownAlpha": 1,
  "unknownBeta": 0,
  "score": 1,
  "unknownScore": 1
}

but all satellites - were updated
curl -s 'http://192.168.1.20:14003/api/sno/satellites' | jq .audits
[
  {
    "auditScore": 1,
    "suspensionScore": 1,
    "onlineScore": 1,
    "satelliteName": "us2.tardigrade.io:7777"
  },
  {
    "auditScore": 1,
    "suspensionScore": 1,
    "onlineScore": 1,
    "satelliteName": "saltlake.tardigrade.io:7777"
  },
  {
    "auditScore": 1,
    "suspensionScore": 0.9997709,
    "onlineScore": 1,
    "satelliteName": "asia-east-1.tardigrade.io:7777"
  },
  {
    "auditScore": 1,
    "suspensionScore": 1,
    "onlineScore": 1,
    "satelliteName": "us-central-1.tardigrade.io:7777"
  },
  {
    "auditScore": 0.9999995,
    "suspensionScore": 1,
    "onlineScore": 1,
    "satelliteName": "europe-west-1.tardigrade.io:7777"
  },
  {
    "auditScore": 0.9998991500000001,
    "suspensionScore": 1,
    "onlineScore": 1,
    "satelliteName": "europe-north-1.tardigrade.io:7777"
  }
]

**Comment by anclrii** [comment]
> with one satellite - yes,

Oh that explains it, the api change is happening in satellite endpoint which the exporter takes audit information from currently. Devs highlighted it's coming in `v1.21.1` so not yet.

**Pull request merged**
